SELECT UNIQUE TC.TABLE_NAME AS NOMBRETABLA, TC.COLUMN_NAME AS NOMBRECOLSPK, C.DATA_TYPE AS TIPODEDATO
FROM ALL_CONS_COLUMNS TC
INNER JOIN ALL_TAB_COLUMNS C ON C.TABLE_NAME = TC.TABLE_NAME 
WHERE C.OWNER = 'PARRANDEROS' AND TC.CONSTRAINT_NAME LIKE '%PK%'
ORDER BY NOMBRETABLA ASC, NOMBRECOLSPK