SELECT CONSULTA1.NOMBRE_COLUMNA, CONSULTA1.TABLA, CONSULTA1.numero
FROM ((SELECT COLUMN_NAME NOMBRE_COLUMNA,t.table_name TABLA, count (c.constraint_name) numero
       FROM ALL_TAB_COLUMNS T 
       INNER JOIN ALL_CONSTRAINTS C ON c.table_name = t.table_name
       WHERE t.owner = 'PARRANDEROS' AND REGEXP_LIKE (CONSTRAINT_NAME, COLUMN_NAME)
       GROUP BY COLUMN_NAME, t.table_name) CONSULTA1)
WHERE  REGEXP_LIKE(CONSULTA1.NOMBRE_COLUMNA,'[A-Z].(([A-Z][A-Z])|([A-Z].[A-Z]|[A-Z].[A-Z]|[A-Z].[A-Z]|[A-Z].[A-Z]))');

