alter session set current_schema = Parranderos; 
SELECT C.TABLE_NAME NOMBRETABLA,TC.COLUMN_NAME NOMBRE_COL,TC.DATA_TYPE TIPODATO,C.CONSTRAINT_NAME NOMBRE_RESTR,tc.nullable PERMITE_NULOS
FROM ALL_CONSTRAINTS C
INNER JOIN ALL_TAB_COLUMNS TC ON C.table_name=tc.table_name
WHERE C.OWNER='PARRANDEROS' 
ORDER BY C.TABLE_NAME,TC.COLUMN_NAME,C.CONSTRAINT_NAME;
